# -> Business Problem:   Absenteeism at a company during work time. <a id="sec0"></a>

**To develop a model that will predict the probability of an individual being excessively absent from work.**

The problem is that the business environment of today is more competitive than it used to be.
This leads to increased pressure in the workplace.
Therefore, it is reasonable to expect that unachievable business goals and an elevated risk of unemployment can raise people's stress levels.

The purpose of the business exercise will be to explore whether a person presenting certain characteristics is expected to be away from work at some point in time or not.
In other words, we want to know for how many working hours an employee could be away from work based on information such as 

•	how far they live from their workplace ?
•	how many children and pets they have ?
•	do they have higher education and so on ?

**Data Preprocessing:**
    
First, we will preprocess the data. I will devote a significant amount of time to this step as it is a crucial part of every analytical task.

I will start working on the ‘Absenteeism_data.csv’ file and take it to a usable state in a machine learning algorithm.

# Table of Contents:

2.[Importing the required Library and Dataset](#chapter1)

3.[Removing Irrelevant Data](#sec2)

4.['Reason for Absence' column:{Experimentation}](#sec3)

5.[Splitting a Column into Multiple Dummies {Experimentation}](#sec4)

6.[Concatenating the above columns with my_df](#sec5)

## 1.Importing the required Libraries <a id="chapter1"></a>

In [2]:
import pandas as pd

In [2]:
# raw_csv_data

raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [3]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [4]:
# df
# Copy of initiall Dataset , making sure the initial df won't be modified!

df = raw_csv_data.copy()
df.tail()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [5]:
#Now, save the df Save it to feather
df.to_feather("df1.feather")

In [3]:
# my_df

my_df = pd.read_feather("df1.feather")
## NOTE : the Size is less of feather data file < than CSV file  (LOAD + SAVE time is VERY less)

In [4]:
my_df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [5]:
# Data Visibility problem solution (Both Rows and Columns)   https://datascientyst.com/pandas-show-all-columns-rows/

df_style = my_df.style.set_table_styles([{'selector': 'th,td', 'props': 
                            [('font-size', '10pt'),('border-style','solid'),('border-width','1px')]}])
df_style
# #df.style.set_table_styles([{'selector': 'td', 'props': [('font-size', '12pt'),('border-style','solid'),('border-width','1px')]}])

In [6]:
## Checking for Null Values
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

**We can obsereve there are no null values**

# -> Removing Irrelevant Data <a id="sec2"></a>

**Removing ID Column**

In [8]:
my_df = my_df.drop(['ID'], axis = 1)
my_df

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

# -> 'Reason for Absence' column:{Experimentation}  <a id="sec3"></a>

In [10]:
# Data Visibility problem solution (Both Rows and Columns)
pd.set_option('display.max_rows', None) #To show all the df records!

# To reset the Options
#pd.reset_option("^display")

In [11]:
my_df['Reason for Absence']

0      26
1       0
2      23
3       7
4      23
5      23
6      22
7      23
8      19
9      22
10      1
11      1
12     11
13     11
14     23
15     14
16     23
17     21
18     11
19     23
20     10
21     11
22     13
23     28
24     18
25     25
26     23
27     28
28     18
29     23
30     18
31     18
32     23
33     18
34     23
35     23
36     24
37     11
38     28
39     23
40     23
41     23
42     23
43     19
44     23
45     23
46     23
47     23
48     22
49     14
50      0
51      0
52     23
53     23
54      0
55      0
56     18
57     23
58      0
59     23
60     23
61     23
62     23
63     23
64      0
65     23
66     23
67     23
68     23
69     23
70     23
71     23
72     23
73     23
74     19
75     14
76     28
77     26
78     23
79     28
80     23
81     23
82     13
83     21
84     23
85     10
86     22
87     14
88     23
89      6
90     23
91     21
92     13
93     28
94     28
95     28
96      7
97     23
98     23
99     19
100    23
101    26
102    23
103    26
104    19
105    22
106    28
107    28
108    23
109    22
110    27
111    19
112    23
113    23
114    19
115    27
116    18
117    27
118    23
119    28
120    27
121    27
122    27
123    27
124    27
125    27
126    27
127    27
128    27
129    18
130    18
131    27
132    23
133    27
134    27
135    23
136    22
137    23
138     1
139    11
140    28
141    23
142    28
143    22
144    11
145     1
146    28
147    23
148    23
149    23
150    25
151    18
152    23
153    23
154    19
155    28
156    19
157    19
158    17
159    22
160    13
161    13
162    14
163    13
164    11
165     1
166    26
167    13
168     6
169     8
170    28
171    23
172    14
173    13
174    23
175    11
176    13
177    11
178    11
179    13
180    14
181    28
182    14
183    28
184    28
185    23
186    28
187    13
188    23
189    28
190    28
191    13
192    23
193    23
194    14
195    28
196    28
197    19
198    19
199    12
200    19
201    13
202     7
203     0
204    13
205    28
206    28
207    18
208    19
209     7
210    28
211    12
212    13
213     0
214     0
215     0
216     0
217    11
218    13
219    22
220    19
221    22
222    10
223    23
224    10
225    11
226    23
227    10
228    13
229    13
230    23
231    13
232    22
233    11
234    28
235    28
236    19
237     1
238     5
239    26
240    26
241    18
242    25
243     1
244     1
245    25
246    22
247    26
248    26
249    19
250    19
251     0
252    19
253    19
254    23
255    18
256    13
257    14
258    28
259    23
260    23
261    11
262    23
263    13
264    25
265    23
266    23
267    19
268     8
269     6
270    11
271    23
272    19
273     0
274     9
275    28
276     0
277     0
278    13
279     9
280    23
281    28
282    28
283    26
284    28
285     0
286    28
287     7
288    13
289    24
290    26
291    26
292    22
293     0
294     0
295     1
296     7
297    22
298    28
299     1
300     0
301    19
302    28
303     0
304    23
305    23
306    28
307    28
308    23
309    28
310    10
311     0
312     0
313     0
314     1
315     7
316    23
317    11
318    23
319     6
320    28
321    23
322     1
323    11
324    26
325     0
326    18
327    11
328    25
329    28
330    13
331    12
332    13
333    28
334    10
335    15
336     0
337     0
338    23
339    12
340    28
341    28
342    23
343    28
344    28
345     4
346    28
347    28
348    23
349    25
350    25
351    28
352    13
353    14
354    26
355    28
356    28
357    19
358    23
359    19
360    23
361    13
362    23
363    26
364     3
365    26
366    26
367    28
368    28
369    28
370    27
371     7
372    22
373    28
374    23
375    27
376    27
377    10
378    26
379    27
380    22
381    27
382    23
383    23
384    11
385    27
386    27
387    10
388    27
389    27
390    18
391    19
392    28
393    28
394    28
395    22
396    22
397    22
398    28
399    22
400     0
401    21
402    23
403    14
404    13
405     0
406     0
407     0
408    28
409    22
410    19
411    28
412    28
413    28
414    26
415    22
416    26
417    23
418    28
419    23
420    13
421    28
422    28
423    28
424    11
425    13
426    23
427    10
428    23
429    28
430    23
431    28
432    11
433     8
434    18
435    25
436    13
437    25
438    28
439     1
440    23
441    23
442    28
443    28
444    23
445    28
446     0
447    13
448    28
449    28
450    28
451    26
452    28
453    23
454    23
455     5
456    21
457    28
458    11
459    13
460    23
461    25
462    13
463     7
464    25
465    26
466    26
467    28
468    15
469    23
470    28
471     9
472    28
473    23
474    22
475    22
476    26
477    28
478    28
479    23
480    25
481    25
482    28
483    28
484    26
485    26
486    28
487    25
488    25
489    23
490    23
491    28
492    28
493    28
494    28
495    28
496    28
497    28
498    23
499    28
500    23
501    23
502    23
503    23
504    23
505    23
506    22
507     4
508    11
509    26
510    14
511    28
512    23
513    23
514    23
515    23
516    23
517    23
518    23
519    26
520    28
521     1
522    23
523    10
524    13
525    10
526    10
527    23
528     6
529    10
530     0
531    13
532    21
533    28
534     2
535    28
536     9
537    24
538     1
539    23
540    22
541    28
542    13
543    14
544    28
545    23
546     8
547    23
548     0
549     0
550    14
551     0
552    23
553    26
554    28
555    13
556    28
557    23
558    13
559    23
560    23
561    14
562    18
563    26
564    18
565    13
566    23
567    23
568    23
569    18
570    12
571    12
572    25
573    25
574    13
575    25
576    10
577    18
578    27
579    18
580    27
581    27
582    13
583    27
584    27
585    13
586    23
587     1
588    27
589    28
590    27
591    27
592    28
593    27
594    19
595    27
596     7
597    27
598    27
599    25
600    13
601    23
602    27
603    12
604    27
605    27
606    13
607    27
608    25
609    25
610    27
611     7
612    27
613    23
614    25
615    27
616    27
617    25
618    27
619    23
620    25
621    25
622    12
623    27
624    27
625    27
626    25
627    27
628    25
629    19
630    13
631    27
632    27
633    27
634    10
635    13
636    27
637     7
638    27
639    23
640    25
641    27
642    23
643    27
644    23
645    27
646    27
647    23
648    13
649    27
650    27
651    13
652    19
653    22
654    13
655    10
656    19
657    19
658    13
659    27
660     7
661    16
662    23
663    23
664    10
665    22
666    27
667    19
668    16
669    27
670    28
671    19
672    14
673    27
674    22
675    19
676    28
677     8
678    26
679    13
680    28
681    14
682    19
683    22
684    27
685    23
686     5
687    28
688     0
689    27
690     0
691    16
692    10
693    10
694    22
695    10
696     6
697    10
698    23
699    28
Name: Reason for Absence, dtype: int64

In [12]:
# Check Min and Max of this column
print(my_df['Reason for Absence'].min())
print(my_df['Reason for Absence'].max())

0
28

## Extracting a list containing Disticnt values only!

In [13]:
my_df['Reason for Absence'].unique()
#pd.unique(my_df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [14]:
len(my_df['Reason for Absence'].unique())

28

**we can conclude the column of interest contains 28 different reasons for absence from work.**

## Let's Sort the above list from items in its argument

In [15]:
sorted(my_df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

Number 20 is missing

**Attention to detail induces us to perform checks that will only solidify the inferences made throughout our analysis later!**

# -> Splitting a Column into Multiple Dummies {Experimentation}  <a id="sec4"></a>

**So, how can we extract some meaning from the above numeric values?**

- Which are the 28 reasons we have sbstituted with numbers here?

In [16]:
my_df.head(2)

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0

## .get_dummies() on 'Reason for Absence'

In [17]:
# reason_column

reason_column = pd.get_dummies(my_df['Reason for Absence'])
reason_column
# Here 0: missig value and 1:single value

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## -> Making sure that there are no multiple reason for absence by introducing a new valriabbe called check

In [18]:
# Creating a new ‘CHECK’ column which contains SUM of all the dummy variables
reason_column['check'] = reason_column.sum(axis = 1)
reason_column

,0,1,2,3,4,5,6,7,8,9,...,19,21,22,23,24,25,26,27,28,check
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [19]:
# Now verify if all the above CHECK columns totals to df size
reason_column['check'].sum(axis=0)

700

In [20]:
# Again, Verify that the CHECK column should have ‘1’ throughout and not 0
reason_column['check'].unique()

array([1], dtype=int64)

All this proves that initially the reason for absents column had been flawless, containing no missing or incorrect values.

At this stage, we should remove the check column with the use of the drop method.

In [23]:
reason_column = reason_column.drop(['check'], axis = 1)
reason_column

,0,1,2,3,4,5,6,7,8,9,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## -> Removing 0th Dummy Variable, and DV Statistical Importance
**Dropping the 0th column**

 from a statistical perspective we will drop the first column of our table.There is a solid mathematical explanation for this step
 
http://qr.ae/TUTz9q    econometric logic and intuition with math!

We will drop the reason, zero dummy variable in Python, we are going to do this because we want to avoid potential multicollinearity issues.
the motivation for us to drop the first column, reason 0, goes like this.

In our analysis, the dummy variables will be of the same type, however there will be 28 (and hence the reasoning will be applied for n = 28 dummies).

If a person has been absent due to reason 0, this means they have been away from work for an unknown reason. Hence, this column acts like the baseline, and all the rest are represented in comparison to this.
 

As a consequence, dropping this column would allow us to only conduct the analysis for the reasons we are aware of. 
And that’s exactly what we want to do - explore whether or not a specific known reason for absence induces an individual to be excessively absent from work. 

That’s why we don’t really need to keep in our data set information about someone who has been away due to an unknown reason

In [24]:
# reason_columns

reason_columns = pd.get_dummies(my_df['Reason for Absence'], drop_first = True)

In [25]:
reason_columns
# So, we have successfully droppes the 0th column
## Here, we see there are too many variables (it would be a good idea to group them according to a common characteristic and )

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## -> Grouping - Transforming Dummy Variables into Categorical Variables

In [26]:
my_df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [27]:
my_df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

## We will Divide them into Groups of 4:


**Reasons 1 to 14 are all related to various diseases -> This could constitute our first group or class**

**2nd  class instead could include reasons from 15 to 17, as they are all somehow related to pregnancy and giving birth.**

**Group 3 would include reasons 18, 19, 20 and 21, as they are all about poisoning or signs not elsewhere categorized.**

**4th  group represents so-called light reasons for absence, such as a dental appointment, physiotherapy, a medical consultation and others.**

In [28]:
my_df.head(2)

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0

### DROP the "Reason for Absence" Column from my_df dataframe

In [29]:
my_df = my_df.drop(['Reason for Absence'], axis = 1)
my_df

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,31/05/2018,291,31,40,237.656,25,1,1,1,2

## Using LOC method for 4 Seperate Groups {Experimentation}

reason_column.loc[]

In [30]:
# for 1st Group
reason_column.loc[:, 1:14]

     1  2  3  4  5  6  7  8  9  10  11  12  13  14
0    0  0  0  0  0  0  0  0  0   0   0   0   0   0
1    0  0  0  0  0  0  0  0  0   0   0   0   0   0
2    0  0  0  0  0  0  0  0  0   0   0   0   0   0
3    0  0  0  0  0  0  1  0  0   0   0   0   0   0
4    0  0  0  0  0  0  0  0  0   0   0   0   0   0
5    0  0  0  0  0  0  0  0  0   0   0   0   0   0
6    0  0  0  0  0  0  0  0  0   0   0   0   0   0
7    0  0  0  0  0  0  0  0  0   0   0   0   0   0
8    0  0  0  0  0  0  0  0  0   0   0   0   0   0
9    0  0  0  0  0  0  0  0  0   0   0   0   0   0
10   1  0  0  0  0  0  0  0  0   0   0   0   0   0
11   1  0  0  0  0  0  0  0  0   0   0   0   0   0
12   0  0  0  0  0  0  0  0  0   0   1   0   0   0
13   0  0  0  0  0  0  0  0  0   0   1   0   0   0
14   0  0  0  0  0  0  0  0  0   0   0   0   0   0
15   0  0  0  0  0  0  0  0  0   0   0   0   0   1
16   0  0  0  0  0  0  0  0  0   0   0   0   0   0
17   0  0  0  0  0  0  0  0  0   0   0   0   0   0
18   0  0  0  0  0  0  0  0  0   0   1   0   0   0
19   0  0  0  0  0  0  0  0  0   0   0   0   0   0
20   0  0  0  0  0  0  0  0  0   1   0   0   0   0
21   0  0  0  0  0  0  0  0  0   0   1   0   0   0
22   0  0  0  0  0  0  0  0  0   0   0   0   1   0
23   0  0  0  0  0  0  0  0  0   0   0   0   0   0
24   0  0  0  0  0  0  0  0  0   0   0   0   0   0
25   0  0  0  0  0  0  0  0  0   0   0   0   0   0
26   0  0  0  0  0  0  0  0  0   0   0   0   0   0
27   0  0  0  0  0  0  0  0  0   0   0   0   0   0
28   0  0  0  0  0  0  0  0  0   0   0   0   0   0
29   0  0  0  0  0  0  0  0  0   0   0   0   0   0
30   0  0  0  0  0  0  0  0  0   0   0   0   0   0
31   0  0  0  0  0  0  0  0  0   0   0   0   0   0
32   0  0  0  0  0  0  0  0  0   0   0   0   0   0
33   0  0  0  0  0  0  0  0  0   0   0   0   0   0
34   0  0  0  0  0  0  0  0  0   0   0   0   0   0
35   0  0  0  0  0  0  0  0  0   0   0   0   0   0
36   0  0  0  0  0  0  0  0  0   0   0   0   0   0
37   0  0  0  0  0  0  0  0  0   0   1   0   0   0
38   0  0  0  0  0  0  0  0  0   0   0   0   0   0
39   0  0  0  0  0  0  0  0  0   0   0   0   0   0
40   0  0  0  0  0  0  0  0  0   0   0   0   0   0
41   0  0  0  0  0  0  0  0  0   0   0   0   0   0
42   0  0  0  0  0  0  0  0  0   0   0   0   0   0
43   0  0  0  0  0  0  0  0  0   0   0   0   0   0
44   0  0  0  0  0  0  0  0  0   0   0   0   0   0
45   0  0  0  0  0  0  0  0  0   0   0   0   0   0
46   0  0  0  0  0  0  0  0  0   0   0   0   0   0
47   0  0  0  0  0  0  0  0  0   0   0   0   0   0
48   0  0  0  0  0  0  0  0  0   0   0   0   0   0
49   0  0  0  0  0  0  0  0  0   0   0   0   0   1
50   0  0  0  0  0  0  0  0  0   0   0   0   0   0
51   0  0  0  0  0  0  0  0  0   0   0   0   0   0
52   0  0  0  0  0  0  0  0  0   0   0   0   0   0
53   0  0  0  0  0  0  0  0  0   0   0   0   0   0
54   0  0  0  0  0  0  0  0  0   0   0   0   0   0
55   0  0  0  0  0  0  0  0  0   0   0   0   0   0
56   0  0  0  0  0  0  0  0  0   0   0   0   0   0
57   0  0  0  0  0  0  0  0  0   0   0   0   0   0
58   0  0  0  0  0  0  0  0  0   0   0   0   0   0
59   0  0  0  0  0  0  0  0  0   0   0   0   0   0
60   0  0  0  0  0  0  0  0  0   0   0   0   0   0
61   0  0  0  0  0  0  0  0  0   0   0   0   0   0
62   0  0  0  0  0  0  0  0  0   0   0   0   0   0
63   0  0  0  0  0  0  0  0  0   0   0   0   0   0
64   0  0  0  0  0  0  0  0  0   0   0   0   0   0
65   0  0  0  0  0  0  0  0  0   0   0   0   0   0
66   0  0  0  0  0  0  0  0  0   0   0   0   0   0
67   0  0  0  0  0  0  0  0  0   0   0   0   0   0
68   0  0  0  0  0  0  0  0  0   0   0   0   0   0
69   0  0  0  0  0  0  0  0  0   0   0   0   0   0
70   0  0  0  0  0  0  0  0  0   0   0   0   0   0
71   0  0  0  0  0  0  0  0  0   0   0   0   0   0
72   0  0  0  0  0  0  0  0  0   0   0   0   0   0
73   0  0  0  0  0  0  0  0  0   0   0   0   0   0
74   0  0  0  0  0  0  0  0  0   0   0   0   0   0
75   0  0  0  0  0  0  0  0  0   0   0   0   0   1
76   0  0  0  0  0  0  0  0  0   0   0   0   0   0
77   0  0  0  0  0  0  0  0  0   0   0   0   0   0
78   0  0  0  0  0  0  0  0  0   0   0   0   0   0
79   0  0  0  0  0  0  0  0  0   0   0   0   0   0
80   0  0  0  0  0  0  0  0  0   0   0   0   0   0
81   0  0  0  0  0  0  0  0  0   0   0   0   0   0
82   0  0  0  0  0  0  0  0  0   0   0   0   1   0
83   0  0  0  0  0  0  0  0  0   0   0   0   0   0
84   0  0  0  0  0  0  0  0  0   0   0   0   0   0
85   0  0  0  0  0  0  0  0  0   1   0   0   0   0
86   0  0  0  0  0  0  0  0  0   0   0   0   0   0
87   0  0  0  0  0  0  0  0  0   0   0   0   0   1
88   0  0  0  0  0  0  0  0  0   0   0   0   0   0
89   0  0  0  0  0  1  0  0  0   0   0   0   0   0
90   0  0  0  0  0  0  0  0  0   0   0   0   0   0
91   0  0  0  0  0  0  0  0  0   0   0   0   0   0
92   0  0  0  0  0  0  0  0  0   0   0   0   1   0
93   0  0  0  0  0  0  0  0  0   0   0   0   0   0
94   0  0  0  0  0  0  0  0  0   0   0   0   0   0
95   0  0  0  0  0  0  0  0  0   0   0   0   0   0
96   0  0  0  0  0  0  1  0  0   0   0   0   0   0
97   0  0  0  0  0  0  0  0  0   0   0   0   0   0
98   0  0  0  0  0  0  0  0  0   0   0   0   0   0
99   0  0  0  0  0  0  0  0  0   0   0   0   0   0
100  0  0  0  0  0  0  0  0  0   0   0   0   0   0
101  0  0  0  0  0  0  0  0  0   0   0   0   0   0
102  0  0  0  0  0  0  0  0  0   0   0   0   0   0
103  0  0  0  0  0  0  0  0  0   0   0   0   0   0
104  0  0  0  0  0  0  0  0  0   0   0   0   0   0
105  0  0  0  0  0  0  0  0  0   0   0   0   0   0
106  0  0  0  0  0  0  0  0  0   0   0   0   0   0
107  0  0  0  0  0  0  0  0  0   0   0   0   0   0
108  0  0  0  0  0  0  0  0  0   0   0   0   0   0
109  0  0  0  0  0  0  0  0  0   0   0   0   0   0
110  0  0  0  0  0  0  0  0  0   0   0   0   0   0
111  0  0  0  0  0  0  0  0  0   0   0   0   0   0
112  0  0  0  0  0  0  0  0  0   0   0   0   0   0
113  0  0  0  0  0  0  0  0  0   0   0   0   0   0
114  0  0  0  0  0  0  0  0  0   0   0   0   0   0
115  0  0  0  0  0  0  0  0  0   0   0   0   0   0
116  0  0  0  0  0  0  0  0  0   0   0   0   0   0
117  0  0  0  0  0  0  0  0  0   0   0   0   0   0
118  0  0  0  0  0  0  0  0  0   0   0   0   0   0
119  0  0  0  0  0  0  0  0  0   0   0   0   0   0
120  0  0  0  0  0  0  0  0  0   0   0   0   0   0
121  0  0  0  0  0  0  0  0  0   0   0   0   0   0
122  0  0  0  0  0  0  0  0  0   0   0   0   0   0
123  0  0  0  0  0  0  0  0  0   0   0   0   0   0
124  0  0  0  0  0  0  0  0  0   0   0   0   0   0
125  0  0  0  0  0  0  0  0  0   0   0   0   0   0
126  0  0  0  0  0  0  0  0  0   0   0   0   0   0
127  0  0  0  0  0  0  0  0  0   0   0   0   0   0
128  0  0  0  0  0  0  0  0  0   0   0   0   0   0
129  0  0  0  0  0  0  0  0  0   0   0   0   0   0
130  0  0  0  0  0  0  0  0  0   0   0   0   0   0
131  0  0  0  0  0  0  0  0  0   0   0   0   0   0
132  0  0  0  0  0  0  0  0  0   0   0   0   0   0
133  0  0  0  0  0  0  0  0  0   0   0   0   0   0
134  0  0  0  0  0  0  0  0  0   0   0   0   0   0
135  0  0  0  0  0  0  0  0  0   0   0   0   0   0
136  0  0  0  0  0  0  0  0  0   0   0   0   0   0
137  0  0  0  0  0  0  0  0  0   0   0   0   0   0
138  1  0  0  0  0  0  0  0  0   0   0   0   0   0
139  0  0  0  0  0  0  0  0  0   0   1   0   0   0
140  0  0  0  0  0  0  0  0  0   0   0   0   0   0
141  0  0  0  0  0  0  0  0  0   0   0   0   0   0
142  0  0  0  0  0  0  0  0  0   0   0   0   0   0
143  0  0  0  0  0  0  0  0  0   0   0   0   0   0
144  0  0  0  0  0  0  0  0  0   0   1   0   0   0
145  1  0  0  0  0  0  0  0  0   0   0   0   0   0
146  0  0  0  0  0  0  0  0  0   0   0   0   0   0
147  0  0  0  0  0  0  0  0  0   0   0   0   0   0
148  0  0  0  0  0  0  0  0  0   0   0   0   0   0
149  0  0  0  0  0  0  0  0  0   0   0   0   0   0
150  0  0  0  0  0  0  0  0  0   0   0   0   0   0
151  0  0  0  0  0  0  0  0  0   0   0   0   0   0
152  0  0  0  0  0  0  0  0  0   0   0   0   0   0
153  0  0  0  0  0  0  0  0  0   0   0   0   0   0
154  0  0  0  0  0  0  0  0  0   0   0   0   0   0
155  0  0  0  0  0  0  0  0  0   0   0   0   0   0
156  0  0  0  0  0  0  0  0  0   0   0   0   0   0
157  0  0  0  0  0  0  0  0  0   0   0   0   0   0
158  0  0  0  0  0  0  0  0  0   0   0   0   0   0
159  0  0  0  0  0  0  0  0  0   0   0   0   0   0
160  0  0  0  0  0  0  0  0  0   0   0   0   1   0
161  0  0  0  0  0  0  0  0  0   0   0   0   1   0
162  0  0  0  0  0  0  0  0  0   0   0   0   0   1
163  0  0  0  0  0  0  0  0  0   0   0   0   1   0
164  0  0  0  0  0  0  0  0  0   0   1   0   0   0
165  1  0  0  0  0  0  0  0  0   0   0   0   0   0
166  0  0  0  0  0  0  0  0  0   0   0   0   0   0
167  0  0  0  0  0  0  0  0  0   0   0   0   1   0
168  0  0  0  0  0  1  0  0  0   0   0   0   0   0
169  0  0  0  0  0  0  0  1  0   0   0   0   0   0
170  0  0  0  0  0  0  0  0  0   0   0   0   0   0
171  0  0  0  0  0  0  0  0  0   0   0   0   0   0
172  0  0  0  0  0  0  0  0  0   0   0   0   0   1
173  0  0  0  0  0  0  0  0  0   0   0   0   1   0
174  0  0  0  0  0  0  0  0  0   0   0   0   0   0
175  0  0  0  0  0  0  0  0  0   0   1   0   0   0
176  0  0  0  0  0  0  0  0  0   0   0   0   1   0
177  0  0  0  0  0  0  0  0  0   0   1   0   0   0
178  0  0  0  0  0  0  0  0  0   0   1   0   0   0
179  0  0  0  0  0  0  0  0  0   0   0   0   1   0
180  0  0  0  0  0  0  0  0  0   0   0   0   0   1
181  0  0  0  0  0  0  0  0  0   0   0   0   0   0
182  0  0  0  0  0  0  0  0  0   0   0   0   0   1
183  0  0  0  0  0  0  0  0  0   0   0   0   0   0
184  0  0  0  0  0  0  0  0  0   0   0   0   0   0
185  0  0  0  0  0  0  0  0  0   0   0   0   0   0
186  0  0  0  0  0  0  0  0  0   0   0   0   0   0
187  0  0  0  0  0  0  0  0  0   0   0   0   1   0
188  0  0  0  0  0  0  0  0  0   0   0   0   0   0
189  0  0  0  0  0  0  0  0  0   0   0   0   0   0
190  0  0  0  0  0  0  0  0  0   0   0   0   0   0
191  0  0  0  0  0  0  0  0  0   0   0   0   1   0
192  0  0  0  0  0  0  0  0  0   0   0   0   0   0
193  0  0  0  0  0  0  0  0  0   0   0   0   0   0
194  0  0  0  0  0  0  0  0  0   0   0   0   0   1
195  0  0  0  0  0  0  0  0  0   0   0   0   0   0
196  0  0  0  0  0  0  0  0  0   0   0   0   0   0
197  0  0  0  0  0  0  0  0  0   0   0   0   0   0
198  0  0  0  0  0  0  0  0  0   0   0   0   0   0
199  0  0  0  0  0  0  0  0  0   0   0   1   0   0
200  0  0  0  0  0  0  0  0  0   0   0   0   0   0
201  0  0  0  0  0  0  0  0  0   0   0   0   1   0
202  0  0  0  0  0  0  1  0  0   0   0   0   0   0
203  0  0  0  0  0  0  0  0  0   0   0   0   0   0
204  0  0  0  0  0  0  0  0  0   0   0   0   1   0
205  0  0  0  0  0  0  0  0  0   0   0   0   0   0
206  0  0  0  0  0  0  0  0  0   0   0   0   0   0
207  0  0  0  0  0  0  0  0  0   0   0   0   0   0
208  0  0  0  0  0  0  0  0  0   0   0   0   0   0
209  0  0  0  0  0  0  1  0  0   0   0   0   0   0
210  0  0  0  0  0  0  0  0  0   0   0   0   0   0
211  0  0  0  0  0  0  0  0  0   0   0   1   0   0
212  0  0  0  0  0  0  0  0  0   0   0   0   1   0
213  0  0  0  0  0  0  0  0  0   0   0   0   0   0
214  0  0  0  0  0  0  0  0  0   0   0   0   0   0
215  0  0  0  0  0  0  0  0  0   0   0   0   0   0
216  0  0  0  0  0  0  0  0  0   0   0   0   0   0
217  0  0  0  0  0  0  0  0  0   0   1   0   0   0
218  0  0  0  0  0  0  0  0  0   0   0   0   1   0
219  0  0  0  0  0  0  0  0  0   0   0   0   0   0
220  0  0  0  0  0  0  0  0  0   0   0   0   0   0
221  0  0  0  0  0  0  0  0  0   0   0   0   0   0
222  0  0  0  0  0  0  0  0  0   1   0   0   0   0
223  0  0  0  0  0  0  0  0  0   0   0   0   0   0
224  0  0  0  0  0  0  0  0  0   1   0   0   0   0
225  0  0  0  0  0  0  0  0  0   0   1   0   0   0
226  0  0  0  0  0  0  0  0  0   0   0   0   0   0
227  0  0  0  0  0  0  0  0  0   1   0   0   0   0
228  0  0  0  0  0  0  0  0  0   0   0   0   1   0
229  0  0  0  0  0  0  0  0  0   0   0   0   1   0
230  0  0  0  0  0  0  0  0  0   0   0   0   0   0
231  0  0  0  0  0  0  0  0  0   0   0   0   1   0
232  0  0  0  0  0  0  0  0  0   0   0   0   0   0
233  0  0  0  0  0  0  0  0  0   0   1   0   0   0
234  0  0  0  0  0  0  0  0  0   0   0   0   0   0
235  0  0  0  0  0  0  0  0  0   0   0   0   0   0
236  0  0  0  0  0  0  0  0  0   0   0   0   0   0
237  1  0  0  0  0  0  0  0  0   0   0   0   0   0
238  0  0  0  0  1  0  0  0  0   0   0   0   0   0
239  0  0  0  0  0  0  0  0  0   0   0   0   0   0
240  0  0  0  0  0  0  0  0  0   0   0   0   0   0
241  0  0  0  0  0  0  0  0  0   0   0   0   0   0
242  0  0  0  0  0  0  0  0  0   0   0   0   0   0
243  1  0  0  0  0  0  0  0  0   0   0   0   0   0
244  1  0  0  0  0  0  0  0  0   0   0   0   0   0
245  0  0  0  0  0  0  0  0  0   0   0   0   0   0
246  0  0  0  0  0  0  0  0  0   0   0   0   0   0
247  0  0  0  0  0  0  0  0  0   0   0   0   0   0
248  0  0  0  0  0  0  0  0  0   0   0   0   0   0
249  0  0  0  0  0  0  0  0  0   0   0   0   0   0
250  0  0  0  0  0  0  0  0  0   0   0   0   0   0
251  0  0  0  0  0  0  0  0  0   0   0   0   0   0
252  0  0  0  0  0  0  0  0  0   0   0   0   0   0
253  0  0  0  0  0  0  0  0  0   0   0   0   0   0
254  0  0  0  0  0  0  0  0  0   0   0   0   0   0
255  0  0  0  0  0  0  0  0  0   0   0   0   0   0
256  0  0  0  0  0  0  0  0  0   0   0   0   1   0
257  0  0  0  0  0  0  0  0  0   0   0   0   0   1
258  0  0  0  0  0  0  0  0  0   0   0   0   0   0
259  0  0  0  0  0  0  0  0  0   0   0   0   0   0
260  0  0  0  0  0  0  0  0  0   0   0   0   0   0
261  0  0  0  0  0  0  0  0  0   0   1   0   0   0
262  0  0  0  0  0  0  0  0  0   0   0   0   0   0
263  0  0  0  0  0  0  0  0  0   0   0   0   1   0
264  0  0  0  0  0  0  0  0  0   0   0   0   0   0
265  0  0  0  0  0  0  0  0  0   0   0   0   0   0
266  0  0  0  0  0  0  0  0  0   0   0   0   0   0
267  0  0  0  0  0  0  0  0  0   0   0   0   0   0
268  0  0  0  0  0  0  0  1  0   0   0   0   0   0
269  0  0  0  0  0  1  0  0  0   0   0   0   0   0
270  0  0  0  0  0  0  0  0  0   0   1   0   0   0
271  0  0  0  0  0  0  0  0  0   0   0   0   0   0
272  0  0  0  0  0  0  0  0  0   0   0   0   0   0
273  0  0  0  0  0  0  0  0  0   0   0   0   0   0
274  0  0  0  0  0  0  0  0  1   0   0   0   0   0
275  0  0  0  0  0  0  0  0  0   0   0   0   0   0
276  0  0  0  0  0  0  0  0  0   0   0   0   0   0
277  0  0  0  0  0  0  0  0  0   0   0   0   0   0
278  0  0  0  0  0  0  0  0  0   0   0   0   1   0
279  0  0  0  0  0  0  0  0  1   0   0   0   0   0
280  0  0  0  0  0  0  0  0  0   0   0   0   0   0
281  0  0  0  0  0  0  0  0  0   0   0   0   0   0
282  0  0  0  0  0  0  0  0  0   0   0   0   0   0
283  0  0  0  0  0  0  0  0  0   0   0   0   0   0
284  0  0  0  0  0  0  0  0  0   0   0   0   0   0
285  0  0  0  0  0  0  0  0  0   0   0   0   0   0
286  0  0  0  0  0  0  0  0  0   0   0   0   0   0
287  0  0  0  0  0  0  1  0  0   0   0   0   0   0
288  0  0  0  0  0  0  0  0  0   0   0   0   1   0
289  0  0  0  0  0  0  0  0  0   0   0   0   0   0
290  0  0  0  0  0  0  0  0  0   0   0   0   0   0
291  0  0  0  0  0  0  0  0  0   0   0   0   0   0
292  0  0  0  0  0  0  0  0  0   0   0   0   0   0
293  0  0  0  0  0  0  0  0  0   0   0   0   0   0
294  0  0  0  0  0  0  0  0  0   0   0   0   0   0
295  1  0  0  0  0  0  0  0  0   0   0   0   0   0
296  0  0  0  0  0  0  1  0  0   0   0   0   0   0
297  0  0  0  0  0  0  0  0  0   0   0   0   0   0
298  0  0  0  0  0  0  0  0  0   0   0   0   0   0
299  1  0  0  0  0  0  0  0  0   0   0   0   0   0
300  0  0  0  0  0  0  0  0  0   0   0   0   0   0
301  0  0  0  0  0  0  0  0  0   0   0   0   0   0
302  0  0  0  0  0  0  0  0  0   0   0   0   0   0
303  0  0  0  0  0  0  0  0  0   0   0   0   0   0
304  0  0  0  0  0  0  0  0  0   0   0   0   0   0
305  0  0  0  0  0  0  0  0  0   0   0   0   0   0
306  0  0  0  0  0  0  0  0  0   0   0   0   0   0
307  0  0  0  0  0  0  0  0  0   0   0   0   0   0
308  0  0  0  0  0  0  0  0  0   0   0   0   0   0
309  0  0  0  0  0  0  0  0  0   0   0   0   0   0
310  0  0  0  0  0  0  0  0  0   1   0   0   0   0
311  0  0  0  0  0  0  0  0  0   0   0   0   0   0
312  0  0  0  0  0  0  0  0  0   0   0   0   0   0
313  0  0  0  0  0  0  0  0  0   0   0   0   0   0
314  1  0  0  0  0  0  0  0  0   0   0   0   0   0
315  0  0  0  0  0  0  1  0  0   0   0   0   0   0
316  0  0  0  0  0  0  0  0  0   0   0   0   0   0
317  0  0  0  0  0  0  0  0  0   0   1   0   0   0
318  0  0  0  0  0  0  0  0  0   0   0   0   0   0
319  0  0  0  0  0  1  0  0  0   0   0   0   0   0
320  0  0  0  0  0  0  0  0  0   0   0   0   0   0
321  0  0  0  0  0  0  0  0  0   0   0   0   0   0
322  1  0  0  0  0  0  0  0  0   0   0   0   0   0
323  0  0  0  0  0  0  0  0  0   0   1   0   0   0
324  0  0  0  0  0  0  0  0  0   0   0   0   0   0
325  0  0  0  0  0  0  0  0  0   0   0   0   0   0
326  0  0  0  0  0  0  0  0  0   0   0   0   0   0
327  0  0  0  0  0  0  0  0  0   0   1   0   0   0
328  0  0  0  0  0  0  0  0  0   0   0   0   0   0
329  0  0  0  0  0  0  0  0  0   0   0   0   0   0
330  0  0  0  0  0  0  0  0  0   0   0   0   1   0
331  0  0  0  0  0  0  0  0  0   0   0   1   0   0
332  0  0  0  0  0  0  0  0  0   0   0   0   1   0
333  0  0  0  0  0  0  0  0  0   0   0   0   0   0
334  0  0  0  0  0  0  0  0  0   1   0   0   0   0
335  0  0  0  0  0  0  0  0  0   0   0   0   0   0
336  0  0  0  0  0  0  0  0  0   0   0   0   0   0
337  0  0  0  0  0  0  0  0  0   0   0   0   0   0
338  0  0  0  0  0  0  0  0  0   0   0   0   0   0
339  0  0  0  0  0  0  0  0  0   0   0   1   0   0
340  0  0  0  0  0  0  0  0  0   0   0   0   0   0
341  0  0  0  0  0  0  0  0  0   0   0   0   0   0
342  0  0  0  0  0  0  0  0  0   0   0   0   0   0
343  0  0  0  0  0  0  0  0  0   0   0   0   0   0
344  0  0  0  0  0  0  0  0  0   0   0   0   0   0
345  0  0  0  1  0  0  0  0  0   0   0   0   0   0
346  0  0  0  0  0  0  0  0  0   0   0   0   0   0
347  0  0  0  0  0  0  0  0  0   0   0   0   0   0
348  0  0  0  0  0  0  0  0  0   0   0   0   0   0
349  0  0  0  0  0  0  0  0  0   0   0   0   0   0
350  0  0  0  0  0  0  0  0  0   0   0   0   0   0
351  0  0  0  0  0  0  0  0  0   0   0   0   0   0
352  0  0  0  0  0  0  0  0  0   0   0   0   1   0
353  0  0  0  0  0  0  0  0  0   0   0   0   0   1
354  0  0  0  0  0  0  0  0  0   0   0   0   0   0
355  0  0  0  0  0  0  0  0  0   0   0   0   0   0
356  0  0  0  0  0  0  0  0  0   0   0   0   0   0
357  0  0  0  0  0  0  0  0  0   0   0   0   0   0
358  0  0  0  0  0  0  0  0  0   0   0   0   0   0
359  0  0  0  0  0  0  0  0  0   0   0   0   0   0
360  0  0  0  0  0  0  0  0  0   0   0   0   0   0
361  0  0  0  0  0  0  0  0  0   0   0   0   1   0
362  0  0  0  0  0  0  0  0  0   0   0   0   0   0
363  0  0  0  0  0  0  0  0  0   0   0   0   0   0
364  0  0  1  0  0  0  0  0  0   0   0   0   0   0
365  0  0  0  0  0  0  0  0  0   0   0   0   0   0
366  0  0  0  0  0  0  0  0  0   0   0   0   0   0
367  0  0  0  0  0  0  0  0  0   0   0   0   0   0
368  0  0  0  0  0  0  0  0  0   0   0   0   0   0
369  0  0  0  0  0  0  0  0  0   0   0   0   0   0
370  0  0  0  0  0  0  0  0  0   0   0   0   0   0
371  0  0  0  0  0  0  1  0  0   0   0   0   0   0
372  0  0  0  0  0  0  0  0  0   0   0   0   0   0
373  0  0  0  0  0  0  0  0  0   0   0   0   0   0
374  0  0  0  0  0  0  0  0  0   0   0   0   0   0
375  0  0  0  0  0  0  0  0  0   0   0   0   0   0
376  0  0  0  0  0  0  0  0  0   0   0   0   0   0
377  0  0  0  0  0  0  0  0  0   1   0   0   0   0
378  0  0  0  0  0  0  0  0  0   0   0   0   0   0
379  0  0  0  0  0  0  0  0  0   0   0   0   0   0
380  0  0  0  0  0  0  0  0  0   0   0   0   0   0
381  0  0  0  0  0  0  0  0  0   0   0   0   0   0
382  0  0  0  0  0  0  0  0  0   0   0   0   0   0
383  0  0  0  0  0  0  0  0  0   0   0   0   0   0
384  0  0  0  0  0  0  0  0  0   0   1   0   0   0
385  0  0  0  0  0  0  0  0  0   0   0   0   0   0
386  0  0  0  0  0  0  0  0  0   0   0   0   0   0
387  0  0  0  0  0  0  0  0  0   1   0   0   0   0
388  0  0  0  0  0  0  0  0  0   0   0   0   0   0
389  0  0  0  0  0  0  0  0  0   0   0   0   0   0
390  0  0  0  0  0  0  0  0  0   0   0   0   0   0

In [31]:
# reasons_type_1 
reason_column.loc[:,1:14].max(axis=1)  #returns the highest value

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    1
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    1
165    1
166    0
167    1
168    1
169    1
170    0
171    0
172    1
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    1
181    0
182    1
183    0
184    0
185    0
186    0
187    1
188    0
189    0
190    0
191    1
192    0
193    0
194    1
195    0
196    0
197    0
198    0
199    1
200    0
201    1
202    1
203    0
204    1
205    0
206    0
207    0
208    0
209    1
210    0
211    1
212    1
213    0
214    0
215    0
216    0
217    1
218    1
219    0
220    0
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    1
229    1
230    0
231    1
232    0
233    1
234    0
235    0
236    0
237    1
238    1
239    0
240    0
241    0
242    0
243    1
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    1
257    1
258    0
259    0
260    0
261    1
262    0
263    1
264    0
265    0
266    0
267    0
268    1
269    1
270    1
271    0
272    0
273    0
274    1
275    0
276    0
277    0
278    1
279    1
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    1
288    1
289    0
290    0
291    0
292    0
293    0
294    0
295    1
296    1
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    1
311    0
312    0
313    0
314    1
315    1
316    0
317    1
318    0
319    1
320    0
321    0
322    1
323    1
324    0
325    0
326    0
327    1
328    0
329    0
330    1
331    1
332    1
333    0
334    1
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    0
343    0
344    0
345    1
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    1
354    0
355    0
356    0
357    0
358    0
359    0
360    0
361    1
362    0
363    0
364    1
365    0
366    0
367    0
368    0
369    0
370    0
371    1
372    0
373    0
374    0
375    0
376    0
377    1
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    1
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    0
402    0
403    1
404    1
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    1
421    0
422    0
423    0
424    1
425    1
426    0
427    1
428    0
429    0
430    0
431    0
432    1
433    1
434    0
435    0
436    1
437    0
438    0
439    1
440    0
441    0
442    0
443    0
444    0
445    0
446    0
447    1
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    1
456    0
457    0
458    1
459    1
460    0
461    0
462    1
463    1
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    0
507    1
508    1
509    0
510    1
511    0
512    0
513    0
514    0
515    0
516    0
517    0
518    0
519    0
520    0
521    1
522    0
523    1
524    1
525    1
526    1
527    0
528    1
529    1
530    0
531    1
532    0
533    0
534    1
535    0
536    1
537    0
538    1
539    0
540    0
541    0
542    1
543    1
544    0
545    0
546    1
547    0
548    0
549    0
550    1
551    0
552    0
553    0
554    0
555    1
556    0
557    0
558    1
559    0
560    0
561    1
562    0
563    0
564    0
565    1
566    0
567    0
568    0
569    0
570    1
571    1
572    0
573    0
574    1
575    0
576    1
577    0
578    0
579    0
580    0
581    0
582    1
583    0
584    0
585    1
586    0
587    1
588    0
589    0
590    0
591    0
592    0
593    0
594    0
595    0
596    1
597    0
598    0
599    0
600    1
601    0
602    0
603    1
604    0
605    0
606    1
607    0
608    0
609    0
610    0
611    1
612    0
613    0
614    0
615    0
616    0
617    0
618    0
619    0
620    0
621    0
622    1
623    0
624    0
625    0
626    0
627    0
628    0
629    0
630    1
631    0
632    0
633    0
634    1
635    1
636    0
637    1
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    1
649    0
650    0
651    1
652    0
653    0
654    1
655    1
656    0
657    0
658    1
659    0
660    1
661    0
662    0
663    0
664    1
665    0
666    0
667    0
668    0
669    0
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
dtype: uint8

## Computing for all the Groups now and Storing in respective variables

In [32]:
reasons_type_1 = reason_column.loc[:,1:14].max(axis=1)
reasons_type_2 = reason_column.loc[:,15:17].max(axis=1)
reasons_type_3 = reason_column.loc[:,18:21].max(axis=1)
reasons_type_2 = reason_column.loc[:,22:].max(axis=1)

# ->  Concatenating the above columns with my_df <a id="sec5"></a>

Adding newly created reason type columns to this data frame 
the pandas concatenation function will do the job to the existing D.F.

In [33]:
my_df

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [34]:
# df1:

# Concatenating Columns:
df1 = pd.concat([my_df, reasons_type_1, reasons_type_2, reasons_type_3, reasons_type_3], 
                axis = 1)

In [35]:
df1.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,1,0,0
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,1,0,0
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,1,0,0

## -> Renaming the concatenated columns!

In [36]:
df1.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [37]:
# creating a new list and assigning it's elements as the column names of df1
column_names = ['Date', 'Transportation Expense',
                'Distance to Work', 'Age', 'Daily Work Load Average',
                'Body Mass Index', 'Education', 'Children', 'Pets',
                'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [38]:
# integrating the new column names!

df1.columns = column_names

In [39]:
df1

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,1,0,0
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,1,0,0
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8,1,0,0,0
696,23/05/2018,225,26,28,237.656,24,1,1,2,3,1,0,0,0
697,24/05/2018,330,16,28,237.656,25,2,0,0,8,1,0,0,0
698,24/05/2018,235,16,32,237.656,25,3,0,0,2,0,1,0,0
699,31/05/2018,291,31,40,237.656,25,1,1,1,2,0,1,0,0

# -> Changing Column Order in Pandas DataFrame

## Re-ordering Columns of df1:

In [40]:
df1.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1',
       'Reason_2', 'Reason_3', 'Reason_4'], dtype=object)

In [41]:
# Create a Column list again

column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age', 
                          'Daily Work Load Average', 'Body Mass Index', 'Education', 
                          'Children','Pets', 'Absenteeism Time in Hours']

In [42]:
# integrating the column arrangements

df1 = df1[column_names_reordered]

In [43]:
df1.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,1,0,0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,1,0,0,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,1,0,0,23/07/2015,289,36,33,239.554,30,1,2,1,2

### -> Implementing Checkpoints. Making a COPY!!

In [44]:
# df1_mod

df1_mod = df1.copy()

**My Habit of making such copies of DataFrames on check points while coding in genral**

# -> Exploring the Initial "Date" Column

## Converting the Date values into timestamp & thus Converting the entire Date variable from object to datetime64[ns] for Month & Week Extraction

In [45]:
# Check the data types:

df1_mod.info()
## Date -> object Dtype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    uint8
 1   Reason_2                   700 non-null    uint8
 2   Reason_3                   700 non-null    uint8
 3   Reason_4                   700 non-null    uint8
 4   Date                       700 non-null    object
 5   Transportation Expense     700 non-null    int64
 6   Distance to Work           700 non-null    int64
 7   Age                        700 non-null    int64
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64
 10  Education                  700 non-null    int64
 11  Children                   700 non-null    int64
 12  Pets                       700 non-null    int64
 13  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(8), object(1), uint8(4)
memory usage: 57.5+ KB

In [46]:
# Check the type of a value in df1_mod of date column
type(df1_mod['Date'][0])

# the values inside date column are String!

str

In [47]:
import warnings
warnings.filterwarnings("ignore")

In [48]:
# Now CONVERT the Date values into timestamp & thus Converting the entire Date variable from object to datetime64[ns] 

df1_mod['Date'] = pd.to_datetime(df1_mod['Date'])

In [49]:
# Validating the result:

type(df1_mod['Date'])

pandas.core.series.Series

In [50]:
type(df1_mod['Date'][0])

# Now, the values inside date column are Timestamp!

pandas._libs.tslibs.timestamps.Timestamp

In [51]:
df1_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    uint8
 1   Reason_2                   700 non-null    uint8
 2   Reason_3                   700 non-null    uint8
 3   Reason_4                   700 non-null    uint8
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64
 6   Distance to Work           700 non-null    int64
 7   Age                        700 non-null    int64
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64
 10  Education                  700 non-null    int64
 11  Children                   700 non-null    int64
 12  Pets                       700 non-null    int64
 13  Absenteeism Time in Hours  700 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(8), uint8(4)
memory usage: 57.5 KB

# -> Using the "Date" Column to:
## A. Extracting the Appropriate Month Value

In [52]:
# df1_mod1

# Create a Checkpoint!
df1_mod1 = df1_mod.copy()

In [53]:
df1_mod1['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
5     2015-10-07
6     2015-07-17
7     2015-07-24
8     2015-06-07
9     2015-07-13
10    2015-07-20
11    2015-07-14
12    2015-07-15
13    2015-07-15
14    2015-07-15
15    2015-07-17
16    2015-07-17
17    2015-07-27
18    2015-07-30
19    2015-05-08
20    2015-12-08
21    2015-03-08
22    2015-10-08
23    2015-08-14
24    2015-08-17
25    2015-08-24
26    2015-04-08
27    2015-12-08
28    2015-08-19
29    2015-08-28
30    2015-08-17
31    2015-08-27
32    2015-08-27
33    2015-08-17
34    2015-08-17
35    2015-08-17
36    2015-04-08
37    2015-08-20
38    2015-08-21
39    2015-08-28
40    2015-01-09
41    2015-07-09
42    2015-01-09
43    2015-08-09
44    2015-09-09
45    2015-09-13
46    2015-09-14
47    2015-09-24
48    2015-04-09
49    2015-09-14
50    2015-09-21
51    2015-09-28
52    2015-08-09
53    2015-09-15
54    2015-09-22
55    2015-09-29
56    2015-09-16
57    2015-09-23
58    2015-09-30
59    2015-11-09
60    2015-09-18
61    2015-09-25
62    2015-06-10
63    2015-10-13
64    2015-10-14
65    2015-10-15
66    2015-10-16
67    2015-10-16
68    2015-06-10
69    2015-10-14
70    2015-10-21
71    2015-10-22
72    2015-10-21
73    2015-10-21
74    2015-10-22
75    2015-10-13
76    2015-10-20
77    2015-10-21
78    2015-10-23
79    2015-10-30
80    2015-05-11
81    2015-04-11
82    2015-05-11
83    2015-12-11
84    2015-11-19
85    2015-02-11
86    2015-09-11
87    2015-11-16
88    2015-11-18
89    2015-11-20
90    2015-11-18
91    2015-11-25
92    2015-11-20
93    2015-11-27
94    2015-02-11
95    2015-10-11
96    2015-11-11
97    2015-11-26
98    2015-01-12
99    2015-01-12
100   2015-02-12
101   2015-02-12
102   2015-03-12
103   2015-04-12
104   2015-08-12
105   2015-09-12
106   2015-10-12
107   2015-11-12
108   2015-12-15
109   2015-12-16
110   2015-11-12
111   2015-12-18
112   2015-12-18
113   2016-06-01
114   2016-04-01
115   2016-05-01
116   2016-05-01
117   2016-06-01
118   2016-07-01
119   2016-07-01
120   2016-08-01
121   2016-11-01
122   2016-12-01
123   2016-12-01
124   2016-01-13
125   2016-01-14
126   2016-01-15
127   2016-11-01
128   2016-12-01
129   2016-12-01
130   2016-12-01
131   2016-01-13
132   2016-01-21
133   2016-01-28
134   2016-01-25
135   2016-01-26
136   2016-01-28
137   2016-05-02
138   2016-03-02
139   2016-10-02
140   2016-11-02
141   2016-11-02
142   2016-12-02
143   2016-12-02
144   2016-08-02
145   2016-09-02
146   2016-02-15
147   2016-09-02
148   2016-02-16
149   2016-02-23
150   2016-02-25
151   2016-02-15
152   2016-02-16
153   2016-02-17
154   2016-02-25
155   2016-01-03
156   2016-01-03
157   2016-08-03
158   2016-03-15
159   2016-03-16
160   2016-02-03
161   2016-03-03
162   2016-04-03
163   2016-04-03
164   2016-07-03
165   2016-03-14
166   2016-03-21
167   2016-03-22
168   2016-03-24
169   2016-03-24
170   2016-03-25
171   2016-03-25
172   2016-03-28
173   2016-03-29
174   2016-03-30
175   2016-03-28
176   2016-03-28
177   2016-03-29
178   2016-03-30
179   2016-03-30
180   2016-03-17
181   2016-03-18
182   2016-03-25
183   2016-03-28
184   2016-06-04
185   2016-04-13
186   2016-12-04
187   2016-04-13
188   2016-04-14
189   2016-04-15
190   2016-04-15
191   2016-06-04
192   2016-07-04
193   2016-08-04
194   2016-08-04
195   2016-04-22
196   2016-04-29
197   2016-04-29
198   2016-04-26
199   2016-04-27
200   2016-04-27
201   2016-04-28
202   2016-08-04
203   2016-04-04
204   2016-04-05
205   2016-05-05
206   2016-02-05
207   2016-03-05
208   2016-03-05
209   2016-11-05
210   2016-09-05
211   2016-10-05
212   2016-04-05
213   2016-11-05
214   2016-05-18
215   2016-05-25
216   2016-05-25
217   2016-05-24
218   2016-11-05
219   2016-05-27
220   2016-06-06
221   2016-06-13
222   2016-06-14
223   2016-06-16
224   2016-06-17
225   2016-06-13
226   2016-06-20
227   2016-06-27
228   2016-06-29
229   2016-03-06
230   2016-07-06
231   2016-08-06
232   2016-09-06
233   2016-10-06
234   2016-06-20
235   2016-06-30
236   2016-05-07
237   2016-06-07
238   2016-08-07
239   2016-08-07
240   2016-12-07
241   2016-07-14
242   2016-07-15
243   2016-07-18
244   2016-07-19
245   2016-07-18
246   2016-07-19
247   2016-07-20
248   2016-07-21
249   2016-11-07
250   2016-07-14
251   2016-07-21
252   2016-04-08
253   2016-11-08
254   2016-07-08
255   2016-08-08
256   2016-10-08
257   2016-10-08
258   2016-11-08
259   2016-08-08
260   2016-09-08
261   2016-10-08
262   2016-10-08
263   2016-10-08
264   2016-08-14
265   2016-08-15
266   2016-08-17
267   2016-08-24
268   2016-08-08
269   2016-08-30
270   2016-05-09
271   2016-09-09
272   2016-07-09
273   2016-08-09
274   2016-12-09
275   2016-09-13
276   2016-09-13
277   2016-09-13
278   2016-09-14
279   2016-09-14
280   2016-09-15
281   2016-09-16
282   2016-09-16
283   2016-09-14
284   2016-09-15
285   2016-09-15
286   2016-09-16
287   2016-09-26
288   2016-09-26
289   2016-05-10
290   2016-05-10
291   2016-05-10
292   2016-06-10
293   2016-06-10
294   2016-06-10
295   2016-12-10
296   2016-12-10
297   2016-12-10
298   2016-10-14
299   2016-10-14
300   2016-10-14
301   2016-10-15
302   2016-10-16
303   2016-10-16
304   2016-10-19
305   2016-10-19
306   2016-10-20
307   2016-10-20
308   2016-10-22
309   2016-10-22
310   2016-10-26
311   2016-10-27
312   2016-10-27
313   2016-10-27
314   2016-10-28
315   2016-10-28
316   2016-10-29
317   2016-07-11
318   2016-07-11
319   2016-08-11
320   2016-11-11
321   2016-11-14
322   2016-11-14
323   2016-11-14
324   2016-11-14
325   2016-11-15
326   2016-11-16
327   2016-11-16
328   2016-11-17
329   2016-11-17
330   2016-11-18
331   2016-11-18
332   2016-11-21
333   2016-11-22
334   2016-11-23
335   2016-11-25
336   2016-11-25
337   2016-11-29
338   2016-11-24
339   2016-05-12
340   2016-05-12
341   2016-05-12
342   2016-05-12
343   2016-06-12
344   2016-09-12
345   2016-12-15
346   2016-12-15
347   2016-12-16
348   2016-12-20
349   2016-12-20
350   2016-12-22
351   2016-12-23
352   2016-12-20
353   2016-12-20
354   2016-12-21
355   2016-12-19
356   2016-12-19
357   2016-12-19
358   2017-04-01
359   2017-09-01
360   2017-09-01
361   2017-03-01
362   2017-03-01
363   2017-09-01
364   2017-11-01
365   2017-01-16
366   2017-01-16
367   2017-01-25
368   2017-01-27
369   2017-07-02
370   2017-01-02
371   2017-01-02
372   2017-03-02
373   2017-10-02
374   2017-02-17
375   2017-02-13
376   2017-02-15
377   2017-02-16
378   2017-02-16
379   2017-02-17
380   2017-02-13
381   2017-02-13
382   2017-02-21
383   2017-02-21
384   2017-02-22
385   2017-02-22
386   2017-02-24
387   2017-02-24
388   2017-02-22
389   2017-02-24
390   2017-07-03
391   2017-08-03
392   2017-10-03
393   2017-10-03
394   2017-03-13
395   2017-03-13
396   2017-03-14
397   2017-03-14
398   2017-03-20
399   2017-03-22
400   2017-03-22
401   2017-03-23
402   2017-03-24
403   2017-03-28
404   2017-03-29
405   2017-03-30
406   2017-03-30
407   2017-03-30
408   2017-03-31
409   2017-03-31
410   2017-03-27
411   2017-03-28
412   2017-05-04
413   2017-07-04
414   2017-07-04
415   2017-10-04
416   2017-10-04
417   2017-12-04
418   2017-12-04
419   2017-04-17
420   2017-04-19
421   2017-04-28
422   2017-04-28
423   2017-04-24
424   2017-04-26
425   2017-01-05
426   2017-03-05
427   2017-08-05
428   2017-10-05
429   2017-10-05
430   2017-11-05
431   2017-12-05
432   2017-05-15
433   2017-05-15
434   2017-05-17
435   2017-05-17
436   2017-05-19
437   2017-05-22
438   2017-05-22
439   2017-05-29
440   2017-05-31
441   2017-05-06
442   2017-05-06
443   2017-06-06
444   2017-08-06
445   2017-09-06
446   2017-09-06
447   2017-12-06
448   2017-12-06
449   2017-06-13
450   2017-06-19
451   2017-06-20
452   2017-06-26
453   2017-06-28
454   2017-06-28
455   2017-06-28
456   2017-06-28
457   2017-06-30
458   2017-06-27
459   2017-06-27
460   2017-06-07
461   2017-06-07
462   2017-07-07
463   2017-10-07
464   2017-07-14
465   2017-07-14
466   2017-07-17
467   2017-07-18
468   2017-07-24
469   2017-07-24
470   2017-07-25
471   2017-07-25
472   2017-07-25
473   2017-07-28
474   2017-07-28
475   2017-07-24
476   2017-07-24
477   2017-07-25
478   2017-07-27
479   2017-07-27
480   2017-03-08
481   2017-07-08
482   2017-08-08
483   2017-08-08
484   2017-08-08
485   2017-08-08
486   2017-10-08
487   2017-08-14
488   2017-08-15
489   2017-08-17
490   2017-08-22
491   2017-08-22
492   2017-08-22
493   2017-08-24
494   2017-08-28
495   2017-05-09
496   2017-05-09
497   2017-05-09
498   2017-05-09
499   2017-07-09
500   2017-08-09
501   2017-08-09
502   2017-11-09
503   2017-09-13
504   2017-09-18
505   2017-09-19
506   2017-09-26
507   2017-05-10
508   2017-05-10
509   2017-06-10
510   2017-11-10
511   2017-11-10
512   2017-10-17
513   2017-10-19
514   2017-10-20
515   2017-10-24
516   2017-10-24
517   2017-10-24
518   2017-10-24
519   2017-10-24
520   2017-10-25
521   2017-10-25
522   2017-10-25
523   2017-10-26
524   2017-10-26
525   2017-10-27
526   2017-10-27
527   2017-10-29
528   2017-10-29
529   2017-10-29
530   2017-10-29
531   2017-10-31
532   2017-07-11
533   2017-08-11
534   2017-08-11
535   2017-10-11
536   2017-11-14
537   2017-11-15
538   2017-11-17
539   2017-11-17
540   2017-11-21
541   2017-11-22
542   2017-11-23
543   2017-11-23
544   2017-11-27
545   2017-11-27
546   2017-11-28
547   2017-11-28
548   2017-11-28
549   2017-11-29
550   2017-11-30
551   2017-11-30
552   2017-11-24
553   2017-11-24
554   2017-11-27
555   2017-05-12
556   2017-06-12
557   2017-06-12
558   2017-08-12
559   2017-08-12
560   2017-12-13
561   2017-12-14
562   2017-12-15
563   2017-12-15
564   2017-12-18
565   2017-12-19
566   2017-12-19
567   2017-12-21
568   2017-12-18
569   2017-12-19
570   2018-01-01
571   2018-04-01
572   2018-04-01
573   2018-05-01
574   2018-08-01
575   2018-10-01
576   2018-11-01
577   2018-12-01
578   2018-01-15
579   2018-01-16
580   2018-01-17
581   2018-01-17
582   2018-01-17
583   2018-01-18
584   2018-01-26
585   2018-06-02
586   2018-06-02
587   2018-07-02
588   2018-07-02
589   2018-08-02
590   2018-08-02
591   2018-08-02
592   2018-09-02
593   2018-09-02
594   2018-12-02
595   2018-12-02
596   2018-02-13
597   2018-02-14
598   2018-02-15
599   2018-02-15
600   2018-02-15
601   2018-02-16
602   2018-02-16
603   2018-02-21
604   2018-02-21
605   2018-02-21
606   2018-02-22
607   2018-02-23
608   2018-02-26
609   2018-02-26
610   2018-02-26
611   2018-02-26
612   2018-02-27
613   2018-02-27
614   2018-02-27
615   2018-02-28
616   2018-02-22
617   2018-02-23
618   2018-05-03
619   2018-05-03
620   2018-06-03
621   2018-06-03
622   2018-06-03
623   2018-07-03
624   2018-08-03
625   2018-08-03
626   2018-08-03
627   2018-09-03
628   2018-12-03
629   2018-12-03
630   2018-03-13
631   2018-03-14
632   2018-03-15
633   2018-03-16
634   2018-03-19
635   2018-03-19
636   2018-03-19
637   2018-03-19
638   2018-03-20
639   2018-03-21
640   2018-03-21
641   2018-03-21
642   2018-03-22
643   2018-03-22
644   2018-03-23
645   2018-03-23
646   2018-03-27
647   2018-03-28
648   2018-03-28
649   2018-03-28
650   2018-03-29
651   2018-03-26
652   2018-03-26
653   2018-03-28
654   2018-02-04
655   2018-02-04
656   2018-03-04
657   2018-04-04
658   2018-05-04
659   2018-06-04
660   2018-09-04
661   2018-10-04
662   2018-10-04
663   2018-10-04
664   2018-11-04
665   2018-04-13
666   2018-04-13
667   2018-04-16
668   2018-04-17
669   2018-04-20
670   2018-04-24
671   2018-04-26
672   2018-04-26
673   2018-04-27
674   2018-07-05
675   2018-09-05
676   2018-09-05
677   2018-09-05
678   2018-09-05
679   2018-10-05
680   2018-10-05
681   2018-10-05
682   2018-11-05
683   2018-11-05
684   2018-11-05
685   2018-05-14
686   2018-05-15
687   2018-05-15
688   2018-05-15
689   2018-05-16
690   2018-05-16
691   2018-05-18
692   2018-05-21
693   2018-05-21
694   2018-05-23
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, dtype: datetime64[ns]

In [54]:
# printing the very first record:

df1_mod1['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [55]:
# This is the Month value extraction from 1st record

df1_mod1['Date'][0].month

7

### Creating an Empty List for months and appending only Month values in it !

In [56]:
list_months = []
list_months

[]

In [57]:
df1_mod1.shape  # dimension of df1_mod1 dataframe

(700, 14)

In [58]:
for i in range(df1_mod1.shape[0]):
    list_months.append(df1_mod1['Date'][i].month)

In [59]:
list_months

[7,
 7,
 7,
 7,
 7,
 10,
 7,
 7,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 12,
 3,
 10,
 8,
 8,
 8,
 4,
 12,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 8,
 8,
 1,
 7,
 1,
 8,
 9,
 9,
 9,
 9,
 4,
 9,
 9,
 9,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 11,
 9,
 9,
 6,
 10,
 10,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 4,
 5,
 12,
 11,
 2,
 9,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 2,
 10,
 11,
 11,
 1,
 1,
 2,
 2,
 3,
 4,
 8,
 9,
 10,
 11,
 12,
 12,
 11,
 12,
 12,
 6,
 4,
 5,
 5,
 6,
 7,
 7,
 8,
 11,
 12,
 12,
 1,
 1,
 1,
 11,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 3,
 10,
 11,
 11,
 12,
 12,
 8,
 9,
 2,
 9,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 8,
 3,
 3,
 2,
 3,
 4,
 4,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 4,
 12,
 4,
 4,
 4,
 4,
 6,
 7,
 8,
 8,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 8,
 4,
 4,
 5,
 2,
 3,
 3,
 11,
 9,
 10,
 4,
 11,
 5,
 5,
 5,
 5,
 11,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 7,
 8,
 9,
 10,
 6,
 6,
 5,
 6,
 8,
 8,
 12,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 11,
 7,
 7,
 4,
 11,
 7,
 8,
 10,
 10,
 11,
 8,
 9,
 10,
 10,
 10,
 8,
 8,
 8,
 8,
 8,
 8,
 5,
 9,
 7,
 8,
 12,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 5,
 5,
 5,
 6,
 6,
 6,
 12,
 12,
 12,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 7,
 8,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 5,
 5,
 5,
 5,
 6,
 9,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 4,
 9,
 9,
 3,
 3,
 9,
 11,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 3,
 10,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 7,
 8,
 10,
 10,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 7,
 7,
 10,
 10,
 12,
 12,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 3,
 8,
 10,
 10,
 11,
 12,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 8,
 9,
 9,
 12,
 12,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 10,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 3,
 7,
 8,
 8,
 8,
 8,
 10,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 5,
 5,
 5,
 5,
 7,
 8,
 8,
 11,
 9,
 9,
 9,
 9,
 5,
 5,
 6,
 11,
 11,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 8,
 8,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 5,
 6,
 6,
 8,
 8,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 4,
 4,
 5,
 8,
 10,
 11,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 6,
 6,
 7,
 7,
 8,
 8,
 8,
 9,
 9,
 12,
 12,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 6,
 6,
 6,
 7,
 8,
 8,
 8,
 9,
 12,
 12,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 4,
 5,
 6,
 9,
 10,
 10,
 10,
 11,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 7,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 11,
 11,
 11,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5]

In [60]:
# Introducted a New Variable ‘Month’ out of Date Column
# integrating the new column 'Month_Value'

df1_mod1['Month_Value'] = list_months

In [61]:
df1_mod1.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month_Value
0,0,1,0,0,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,0,1,0,0,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,0,1,0,0,2015-07-23,289,36,33,239.554,30,1,2,1,2,7

**what we just did is:**

It will allow us to check whether in specific months of the year, employees tend to be absent more often compared to other months.

Following the same logic, it may turn out that on certain days of the week, workers may be more prone to be away from the desk than on other days.

We may probably think one would rather leave earlier on Friday than on Monday.

## -> Extracting "Day of the Week"

In [62]:
# using weekday()

df1_mod1['Date'][250].weekday()

3

In [64]:
df1_mod1['Date'][500].weekday()

2

### Creating a Function and then Apply it to the dataframe

In [65]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [66]:
df1_mod1['Day of the Week'] = df1_mod1['Date'].apply(date_to_weekday)

In [67]:
df1_mod1.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month_Value,Day of the Week
0,0,1,0,0,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,1,0,0,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,1,0,0,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

# -> Removing Date column and Re-ordering some columns
## A. ‘Date’ column – dropping it from the df1_mod1 DataFrame.
## B.  Re-ordering the columns in df1_mod1 so that “Month Value” and “Day of the Week” appear exactly where “Date” used to be. That is, between “Reason_4” and “Transportation Expense”.

In [68]:
df1_mod1.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month_Value,Day of the Week
0,0,1,0,0,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,1,0,0,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,1,0,0,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [69]:
df1_mod1 = df1_mod1.drop(['Date'], axis = 1)
df1_mod1.head(2)

,Reason_1,Reason_2,Reason_3,Reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month_Value,Day of the Week
0,0,1,0,0,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,118,13,50,239.554,31,1,1,0,0,7,1

In [70]:
df1_mod1.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month_Value',
       'Day of the Week'], dtype=object)

In [71]:
columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
            'Month_Value','Day of the Week',
           'Transportation Expense', 'Distance to Work', 'Age',
           'Daily Work Load Average', 'Body Mass Index', 'Education',
           'Children', 'Pets', 'Absenteeism Time in Hours']

In [72]:
df1_mod1 = df1_mod1[columns]

In [73]:
df1_mod1.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month_Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,1,0,0,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,1,0,0,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,1,0,0,7,3,289,36,33,239.554,30,1,2,1,2

# Further Analysis of the DataFrame: Next 9 Columns

In [74]:
df1_mod1

,Reason_1,Reason_2,Reason_3,Reason_4,Month_Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,1,0,0,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,1,0,0,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,1,0,0,7,3,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,2,179,22,40,237.656,22,2,2,0,8
696,1,0,0,0,5,2,225,26,28,237.656,24,1,1,2,3
697,1,0,0,0,5,3,330,16,28,237.656,25,2,0,0,8
698,0,1,0,0,5,3,235,16,32,237.656,25,3,0,0,2
699,0,1,0,0,5,3,291,31,40,237.656,25,1,1,1,2

**Transportation expenses**
    
Costs related to business travel, such as fuel parking miles and other charges an employee may claim for reimbursement.

This means transportation is just one of those potential costs in our table. This column contains monthly transportation expenses of an individual measured in dollars.

In [75]:
type(df1_mod1['Transportation Expense'][0])

numpy.int64

**Distance to Work**
    
Kilometers an individual must travel from home to work

Of course, how old a person is could always have an impact on her or his behavior.

In [76]:
type(df1_mod1['Distance to Work'][0])

numpy.int64

**daily work load average**

The average amount of time spent working per day, shown in minutes

In [77]:
type(df1_mod1['Daily Work Load Average'][0])

numpy.float64

**Body mass index**

it is an indicator for an under, normal overweight or obese person.

Logically, people who weigh above the norm for their height often have an additional reason for being absent from work.
including the body mass index in our regression analysis.

In [78]:
type(df1_mod1['Body Mass Index'][0])

numpy.int64

**Education column**

Transform education into a dummy variable.
The map function will help us do that, so what values are stored in the education column instead of scrolling down the table trying to guess whether we'll only see 1s, 2s or 3s,

Applying Python's unique method.

In [79]:
df1_mod1['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [80]:
df1_mod1['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

- Let's combine 2,3,4 into single category

In [81]:
df1_mod1['Education'] = df1_mod1['Education'].map({1:0, 2:1, 3:1, 4:1})

In [82]:
df1_mod1['Education'].unique()

array([0, 1], dtype=int64)

In [83]:
df1_mod1['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [84]:
df1_mod1.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month_Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,1,0,0,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,1,0,0,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,1,0,0,7,3,289,36,33,239.554,30,0,2,1,2

**Absenteeism Time in Hours**

The interpretation of this column is straightforward

It's modification is related to the application of advanced Statistical Techniques

# FINAL Check Point  Make a copy Now!! Saving 'Absenteeism_preprocessed' as CHECK Point for Future Machine Learning Analysis and Model Building

In [85]:
df_preprocessed = df1_mod1.copy()

In [86]:
df_preprocessed

,Reason_1,Reason_2,Reason_3,Reason_4,Month_Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,1,0,0,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,1,0,0,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,1,0,0,7,3,289,36,33,239.554,30,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,8
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,3
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,8
698,0,1,0,0,5,3,235,16,32,237.656,25,1,0,0,2
699,0,1,0,0,5,3,291,31,40,237.656,25,0,1,1,2

In [87]:
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False)